
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author Ville
 */
public class Menu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_Menu;
    
    public Menu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu");
        this.setLayout(null);
        
        jDesktopPane_Menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_Menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_Menu);
    }
    
    
      @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevoUsuario = new javax.swing.JMenuItem();
        jMenuGestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuNuevoProdcuto = new javax.swing.JMenuItem();
        MenuIGestionarProducto = new javax.swing.JMenuItem();
        MenuActualizarStock = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuNuevaCategoria = new javax.swing.JMenuItem();
        MenuGestionarCategoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuNuevaVenta = new javax.swing.JMenuItem();
        jMenuGestionarVenta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        MenuCerrarSesion = new javax.swing.JMenuItem();

        jMenuItem16.setText("jMenuItem16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(158, 206, 211));
        setForeground(new java.awt.Color(158, 206, 211));
        setIconImage(getIconImage());
        setPreferredSize(null);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(158, 206, 211));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconUsuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(190, 50));

        jMenuNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuNuevoUsuario.setText("Nuevo Usuario");
        jMenuNuevoUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevoUsuario);

        jMenuGestionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuGestionarUsuario.setText("Gestionar Usuarios");
        jMenuGestionarUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconProducto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(190, 50));

        MenuNuevoProdcuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuNuevoProdcuto.setText("Nuevo Producto");
        MenuNuevoProdcuto.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuNuevoProdcuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNuevoProdcutoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuNuevoProdcuto);

        MenuIGestionarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuIGestionarProducto.setText("Gestionar Producto");
        MenuIGestionarProducto.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuIGestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIGestionarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuIGestionarProducto);

        MenuActualizarStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuActualizarStock.setText("Actualizar Inventario");
        MenuActualizarStock.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActualizarStockActionPerformed(evt);
            }
        });
        jMenu2.add(MenuActualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconCategorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(190, 50));

        MenuNuevaCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuNuevaCategoria.setText("Nueva Categoria");
        MenuNuevaCategoria.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuNuevaCategoria);

        MenuGestionarCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuGestionarCategoria.setText("Gestionar Categorias");
        MenuGestionarCategoria.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestionarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuGestionarCategoria);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconFacturar.png"))); // NOI18N
        jMenu5.setText("Pagar");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(190, 50));

        jMenuNuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuNuevaVenta.setText("Nueva Venta");
        jMenuNuevaVenta.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevaVentaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuNuevaVenta);

        jMenuGestionarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuGestionarVenta.setText("Gestionar Ventas");
        jMenuGestionarVenta.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuGestionarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionarVentaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuGestionarVenta);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconReportes.png"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(190, 50));

        jMenuItem13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem13.setText("Reportes Categorias");
        jMenuItem13.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem14.setText("Reportes Productos");
        jMenuItem14.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu6.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem15.setText("Reportes Ventas");
        jMenuItem15.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu6.add(jMenuItem15);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconHistorial.png"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(190, 50));

        jMenuItem17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem17.setText("Ver Historial");
        jMenuItem17.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu7.add(jMenuItem17);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconCerrar (1).png"))); // NOI18N
        jMenu8.setText("Cerrar Sesion");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setMinimumSize(new java.awt.Dimension(200, 50));
        jMenu8.setPreferredSize(new java.awt.Dimension(190, 50));

        MenuCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuCerrarSesion.setText("Cerrar Sesion");
        MenuCerrarSesion.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu8.add(MenuCerrarSesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevaVentaActionPerformed
        Venta venta = new Venta();
        jDesktopPane_Menu.add(venta);
        venta.setVisible(true);
    }//GEN-LAST:event_jMenuNuevaVentaActionPerformed

    private void jMenuGestionarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionarVentaActionPerformed
        GestionarVenta gestionarventa = new GestionarVenta();
        jDesktopPane_Menu.add(gestionarventa);
        gestionarventa.setVisible(true);
    }//GEN-LAST:event_jMenuGestionarVentaActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void MenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_MenuCerrarSesionActionPerformed

    private void MenuNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevaCategoriaActionPerformed
        Categoria categoria = new Categoria();
        jDesktopPane_Menu.add(categoria);
        categoria.setVisible(true);

    }//GEN-LAST:event_MenuNuevaCategoriaActionPerformed

    private void MenuGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestionarCategoriaActionPerformed
        GestionarCategoria gestionarcategoria = new GestionarCategoria();
        jDesktopPane_Menu.add(gestionarcategoria);
        gestionarcategoria.setVisible(true);
    }//GEN-LAST:event_MenuGestionarCategoriaActionPerformed

    private void MenuNuevoProdcutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevoProdcutoActionPerformed
        Producto producto = new Producto();
        jDesktopPane_Menu.add(producto);
        producto.setVisible(true);
    }//GEN-LAST:event_MenuNuevoProdcutoActionPerformed

    private void MenuIGestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIGestionarProductoActionPerformed
        GestionarProducto gestionarproducto = new GestionarProducto();
        jDesktopPane_Menu.add(gestionarproducto);
        gestionarproducto.setVisible(true);
    }//GEN-LAST:event_MenuIGestionarProductoActionPerformed

    private void MenuActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActualizarStockActionPerformed
        ActualizarStock actualizarstock = new ActualizarStock();
        jDesktopPane_Menu.add(actualizarstock);
        actualizarstock.setVisible(true);
    }//GEN-LAST:event_MenuActualizarStockActionPerformed

    private void jMenuNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoUsuarioActionPerformed
        Usuario usuario = new Usuario();
        jDesktopPane_Menu.add(usuario);
        usuario.setVisible(true);
    }//GEN-LAST:event_jMenuNuevoUsuarioActionPerformed

    private void jMenuGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionarUsuarioActionPerformed
        try {
            GestionarUsuario gestionarusuario = new GestionarUsuario();
            jDesktopPane_Menu.add(gestionarusuario);
            gestionarusuario.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuGestionarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuActualizarStock;
    private javax.swing.JMenuItem MenuCerrarSesion;
    private javax.swing.JMenuItem MenuGestionarCategoria;
    private javax.swing.JMenuItem MenuIGestionarProducto;
    private javax.swing.JMenuItem MenuNuevaCategoria;
    private javax.swing.JMenuItem MenuNuevoProdcuto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGestionarUsuario;
    private javax.swing.JMenuItem jMenuGestionarVenta;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuNuevaVenta;
    private javax.swing.JMenuItem jMenuNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
